### ISSUE TITLE
Handle auth cancels

### ISSUE THREAD

**Issue by seanfahey** [pete2786/mnw-rails4#2]
When "Sign in with Facebook" is clicked you are redirected to Facebook, which asks to approve authorization.  If "Cancel" is clicked, we are redirected back to a 404 page from the app: http://www.weatherclever.com/auth/failure?message=no_authorization_code&origin=http%3A%2F%2Fwww.weatherclever.com%2F&strategy=facebook#_=_

Could use the parameters there to create a better error page.

**Comment by pete2786** [comment]
Thanks.

**Comment by pete2786** [comment]
Done.
