### ISSUE TITLE
Default/Home location user preference?

### ISSUE THREAD

**Issue by chrisarcand** [pete2786/mnw-rails4#3]
Seems like you should have a preference in Settings for your user to set a "default" or "home" location to be auto-filled on the main page when you visit it while logged in; Faves and Location services are nice, but I'd want my typical location to already be up and going when I visit the site if I used this frequently.

**Comment by pete2786** [comment]
Cool, good idea.

**Comment by pete2786** [comment]
Hacked it in, need to add UI for selecting, right now just the first favorite location.
